### ISSUE TITLE
Jenkins warnings

### ISSUE THREAD

**Issue by gdbtek** [gdbtek/linux-cookbooks#21]
```
Downloading 'http://mirrors.jenkins-ci.org/war/latest/jenkins.war' to '/tmp/20150922-121048-NtyxIney62'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   328    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 60.2M  100 60.2M    0     0  46.3M      0  0:00:01  0:00:01 --:--:-- 67.4M
Sep 22, 2015 12:12:08 PM hudson.remoting.RemoteInvocationHandler$Unexporter run
WARNING: Couldn't clean up oid=3 from null
hudson.remoting.ChannelClosedException: channel is already closed
    at hudson.remoting.Channel.send(Channel.java:575)
    at hudson.remoting.RemoteInvocationHandler$PhantomReferenceImpl.cleanup(RemoteInvocationHandler.java:360)
    at hudson.remoting.RemoteInvocationHandler$PhantomReferenceImpl.access$700(RemoteInvocationHandler.java:319)
    at hudson.remoting.RemoteInvocationHandler$Unexporter.run(RemoteInvocationHandler.java:420)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException
    at hudson.remoting.Channel.close(Channel.java:1160)
    at hudson.remoting.Channel.close(Channel.java:1135)
    at hudson.cli.CLI.close(CLI.java:329)
    at hudson.cli.CLI._main(CLI.java:511)
    at hudson.cli.CLI.main(CLI.java:390)


Version: 1.630
```

**Comment by gdbtek** [comment]
random issue. Look like Jenkins's issue. Closing

**Comment by pritam97** [comment]
Hi Team,

i also got the same issue please provide me the solution.. hoe to fix it. 

BR,
Pritam K

**Comment by gdbtek** [comment]
@pritam97 as I have mentioned, this error is random errors, I don't have a solid solution other than rerun the setup.

**Comment by iennae** [comment]
For folks that are experiencing this error, I believe it might be related to https://issues.jenkins-ci.org/browse/JENKINS-34375. Check your permissions. I see this using the jenkins cli and intermittent issues.

```
[root@8eddbdc330a1 sbin]# "java" -jar "/opt/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 who-am-i
```

Authenticated as: anonymous
Authorities:
  anonymous

Example:

Oct 17, 2016 5:30:07 AM hudson.remoting.RemoteInvocationHandler$Unexporter run
WARNING: Couldn't clean up oid=3 from null
hudson.remoting.ChannelClosedException: channel is already closed
    at hudson.remoting.Channel.send(Channel.java:578)
    at hudson.remoting.RemoteInvocationHandler$PhantomReferenceImpl.cleanup(RemoteInvocationHandler.java:360)
    at hudson.remoting.RemoteInvocationHandler$PhantomReferenceImpl.access$700(RemoteInvocationHandler.java:319)
    at hudson.remoting.RemoteInvocationHandler$Unexporter.run(RemoteInvocationHandler.java:420)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException
    at hudson.remoting.Channel.close(Channel.java:1163)
    at hudson.remoting.Channel.close(Channel.java:1138)
    at hudson.cli.CLI.close(CLI.java:329)
    at hudson.cli.CLI._main(CLI.java:511)
    at hudson.cli.CLI.main(CLI.java:390)

  [root@8eddbdc330a1 sbin]# "java" -jar "/opt/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 list-plugins
ant                       Ant Plugin                           1.2 (1.4)
javadoc                   Javadoc Plugin                       1.1 (1.4)
junit                     JUnit Plugin                         1.2-beta-4 (1.18)
pam-auth                  PAM Authentication plugin            1.1 (1.3)
matrix-auth               Matrix Authorization Strategy Plugin 1.1 (1.4)
antisamy-markup-formatter OWASP Markup Formatter Plugin        1.1 (1.5)
ssh-credentials           SSH Credentials Plugin               1.10 (1.12)
script-security           Script Security Plugin               1.13 (1.23)
cvs                       CVS Plug-in                          2.11 (2.12)
ldap                      LDAP Plugin                          1.11 (1.13)
windows-slaves            Windows Slaves Plugin                1.0 (1.2)
subversion                Subversion Plug-in                   1.54 (2.6)
translation               Translation Assistance plugin        1.10 (1.15)
credentials               Credentials Plugin                   1.18 (2.1.6)
maven-plugin              Maven Integration plugin             2.7.1 (2.13)
external-monitor-job      External Monitor Job Type Plugin     1.4 (1.6)
mailer                    Mailer Plugin                        1.11 (1.18)
matrix-project            Matrix Project Plugin                1.4.1 (1.7.1)
ssh-slaves                SSH Slaves plugin                    1.9 (1.11)

**Comment by oleg-nenashev** [comment]
##### Original issue

Due to whatever reason, the newly created connection from CLI to Jenkins gets terminated. @iennae is right that missing permissions is one of the potential causes. [JENKINS-34375](https://issues.jenkins-ci.org/browse/JENKINS-34375) is likely a similar case.

##### Regarding the warning

Warning message is a bug. You should have received a warning message about channel termination before it. Maybe the message gets redirected somewhere. The next Jenkins releases will likely suppress the issue.
